#puppet setup

version: '2'
services:
    master:
        build:
            context: ./master
        container_name: puppet_master 
        expose:
            - "8140"
        hostname: master
        volumes:
        - ./master/manifests:/etc/puppet/manifests
    agent1:
        build:
            args:
                node: agent1
            context: ./agent
        container_name: puppet_agent1
        hostname: agent1
        depends_on:
            - master
        links:
            - "master:puppet"
    agent2:
        build:
            args:
                node: agent2
            context: ./agent
        container_name: puppet_agent2
        hostname: agent2
        depends_on:
            - master
        links:
            - "master:puppet"
    agent3:
        build:
            args:
                node: agent3
            context: ./agent
        container_name: puppet_agent3
        hostname: agent3
        depends_on:
            - master
        links:
            - "master:puppet"
